#!/bin/sh

branch="$(git symbolic-ref --short HEAD)"

if [ "$branch" = "main" ]; then
    echo "Running tests before committing..."
    pytest test.py
    if [ $? -ne 0 ]; then
        echo "❌ Tests failed. Commit aborted."
        exit 1
    else
        echo "✅ Tests passed."
    fi
fi